var : 
project_name: test
username: root
privateKey: d:/test
host: 402.323.4.2
port: "22"
localPath: D:/workspaces/ngi-sync
remotePath: /home/root
ignores: []
downloads: []
single_sync: []
direct_access:
  config_file: "your ssh config file "
  ssh_configs: 
  - Host: test
    HostName: =host
  ssh_commands: 
  - access_name: Test
    remote_access: ssh -v test

trigger_permission:
  unlink_folder: false
  unlink: false
  change: false
  add: true
